### ISSUE TITLE
Widget compact / full mode in Nova Launcher

### ISSUE THREAD

**Issue by sucat** [romannurik/dashclock#852]
Hi,
When I add the Dash Clock widget to the screen it stays in "compact" mode.
I have to set the widget size much bigger to see the widget in "full" mode.

Still "compact" mode for this size:
![screenshot_2015-05-27-08-59-15](https://cloud.githubusercontent.com/assets/7252341/7831514/50dfa568-044f-11e5-85db-2f8aeb7df3cd.png)

Minimum widget size for "full" mode:
![screenshot_2015-05-27-08-59-25](https://cloud.githubusercontent.com/assets/7252341/7831513/50dc7b04-044f-11e5-97ef-2838ef113e88.png)

Would it be possible to add a flag in settings to force "full" mode and make the content scrollable?
I like when I see detailed notifications in the widget but I cannot reserve over half screen for it.

Android version:5.0.1
Nova Launcher 4.0.1
Samsung Galaxy S4 GT-I9505

**Comment by patto-sk** [comment]
The same issue with Nova Launcher (Android 5). It sometime works but when I restart the phone then DashClock widget appears still in compact mode. It's very annoying. I want to see detailed notifications always.

![screenshot_2015-06-06-20-33-25](https://cloud.githubusercontent.com/assets/766160/8034163/786f287a-0de5-11e5-9062-c96dc94e3355.png)

**Comment by justpastfinish** [comment]
I have the same issue. Galaxy s6 edge, android 5.1.1 and it occurs on both nova prime and action. Launcher 3.

**Comment by Jnormand** [comment]
I'm having a similar issue with Aviate Launcher 

![screenshot_2015-12-28-10-41-05](https://cloud.githubusercontent.com/assets/4730563/12021398/7b1ce81e-ad54-11e5-8c8f-656a05860e01.png)

**Comment by sucat** [comment]
Looks like it's not going to be fixed. Closing the issue.
