### ISSUE TITLE
No weather data available

### ISSUE THREAD

**Issue by thenestor** [romannurik/dashclock#865]
For a few days, the built-in weather extension has shown "No weather data available" in the DashClock widget on my home screen. I tried with custom location (Anaheim, California) and with automatic location, and I got the same result. I assume it's a problem with the Yahoo Weather API, but there isn't another source that I can choose (like openweathermap or yr.no) to test that theory.

**Comment by Jason6g** [comment]
Having same issue. Tried installing better weather and changed to openweathermap with the same result. Clock and other extensions still work well for me, just not the weather.

**Comment by ChgoChad** [comment]
Same issue here... no weather data the past few days

**Comment by Stanzilla** [comment]
Same

**Comment by romannurik** [comment]
Looks like Yahoo changed their API a bit:

To increase the security measure and better serving our YDN customers, weather data source will enforce OAuth 1 starting March 15, 2016. Please update your API calls with OAuth 1 enabled (via the OAuth /v1/yql end point if using YQL) using your Yahoo App key and secret.


In the meantime please try out third party weather extensions!

**Comment by romannurik** [comment]
The more I look at Yahoo's new Weather API stuff, the more I'm thinking of just turning off the built-in weather extension in favor of third parties :( Will try to provide an update in a few days; part of their developer site is down.

**Comment by ChgoChad** [comment]
Roman - I would encourage you not to remove the built-in weather extension!  Relatively speaking, there are only a few third-party weather extensions. Most of them rely on Amber Weather--and while I have nothing against Amber Weather, I don't see the need to install a third program when the extension can be authored to get the weather information directly.  

This leave only a handful of other weather extensions. Unfortunately, the two that I have tried this morning both use Yahoo and are broke as well... 

Perhaps you can **abandon Yahoo** and easily implement the **Forecast.io**, or another API?.

**Comment by romannurik** [comment]
Unfortunately Forecast.io and other weather APIs cost money, which isn't really acceptable for a free app like DashClock.

**Comment by Stanzilla** [comment]
https://play.google.com/store/apps/details?id=net.imatruck.betterweather was updated yesterday and should work in theory, does not in practice for me. Uses OpenWeatherMap API (http://openweathermap.org/api) which sounds like it is free.

**Comment by thenestor** [comment]
I found one that's working for me: DashClock Weather (yr.no)
https://play.google.com/store/apps/details?id=com.ctrlplusz.dashclock.yr

**Comment by Stanzilla** [comment]
Correction, BetterWeather works as well, you just have to grant the location permission manually.

**Comment by JonathanConley** [comment]
Hey Roman,

I'm not very familiar with the issue, but weather.com seems to have an API which Google uses for their weather widget. Is there any way to get that data and to allow the widget shortcut to bring up a weather search to Google's card in the Google App?

https://www.wunderground.com/weather/api/

**Comment by romannurik** [comment]
Unfortunately Weather Underground is also a paid service / has a prohibitively low free quota.

**Comment by JonathanConley** [comment]
Ah, yeah, I see that. Too bad you can't hop onto the Google API key license.

Any way to ask for in-app donations to cover the costs? Or offer a paid version of the app?

**Comment by keckelt** [comment]
Try to change:
http://weather.yahooapis.com/ 
to: 
http://xml.weather.yahoo.com/ 

worked for my own scripts.

**Comment by romannurik** [comment]
I was considering that too but that seems like a short term fix and isn't
official AFAICT?

**Comment by exhuma** [comment]
I've come across this issue as the weather extension is also not working for me. Given that this merge is almost a year old, is it broken again? Or is there something else amiss?

Is the official statement still to use a 3rd party extension?

**Comment by thenestor** [comment]
I've been using the app Arcus Weather, which shows up as a Dashclock
extension, and it works well and looks great.
