### ISSUE TITLE
Moving APP_ID to Build Config

### ISSUE THREAD

**Issue by hkasera** [romannurik/dashclock#866]
Hey @romannurik,

I was wondering that why do we have Yahoo Weather Api app id in the constants file [`YahooWeatherApiConfig `](https://github.com/romannurik/dashclock/blob/master/main/src/main/java/com/google/android/apps/dashclock/weather/YahooWeatherApiConfig.java) rather than in Gradle Build Config. Isn't it a best practice to have these API keys and secrets in the build config?

Let me know your thoughts on the same.

Thanks,
Harshita

**Comment by romannurik** [comment]
I don't actually know about the best practice here but given the config doesn't change between debug/release builds I figure this belongs in a separate file?

**Comment by hkasera** [comment]
@romannurik Yes makes sense! Thank you :+1:
